services:
  notify:
    build:
      dockerfile: Dockerfile
    container_name: notify
    volumes:
      - ./static:/app/static
      - ./template:/app/template
      - ./keys:/app/keys
      - ./internal/sqlite:/app/internal/sqlite
    environment:
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - EMAIL=${EMAIL}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - SCHEDULE_TIME_HOUR=${SCHEDULE_TIME_HOUR}
      - SCHEDULE_TIME_MINUTE=${SCHEDULE_TIME_MINUTE}
      - TZ=Europe/Berlin
    networks:
      - home_network

networks:
  home_network:
    external: true