services:
  notify:
    build:
      dockerfile: Dockerfile
    container_name: notify
    volumes:
      - ./static:/app/static
      - ./template:/app/template
      - ./keys:/app/keys
      - ./internal/sqlite:/app/internal/sqlite
    environment:
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - EMAIL=${EMAIL}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - TZ=Europe/Berlin
    networks:
      - notify_network
    restart: 'unless-stopped'

networks:
  notify_network:
    external: true
    name: ${NETWORK_NAME:-notify_default_network}